apiVersion: v1
kind: Service
metadata:
    name: "bankingkc-a211"
    labels:
        app: "bankingkc-a211"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "bankingkc-a211"