on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: bankingsystemr.azurecr.io
        username: ${{ secrets.acr_bankingsystemr_username }}
        password: ${{ secrets.acr_bankingsystemr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t bankingsystemr.azurecr.io/bankingkc:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push bankingsystemr.azurecr.io/bankingkc:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bankingkc_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bankingkc9968 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bankingkc9968`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bankingkc9968
        container-registry-url: bankingsystemr.azurecr.io
        container-registry-username: ${{ secrets.acr_bankingsystemr_username }}
        container-registry-password: ${{ secrets.acr_bankingsystemr_password }}
        secret-name: bankingkcdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: bankingkc9968
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          bankingsystemr.azurecr.io/bankingkc:${{ github.sha }}
        imagepullsecrets: |
          bankingkcdockerauth
