on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: accountreg.azurecr.io
        username: ${{ secrets.acr_accountreg_username }}
        password: ${{ secrets.acr_accountreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t accountreg.azurecr.io/accountkuber:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push accountreg.azurecr.io/accountkuber:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_accountkuber_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep accountkuber8aa6 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace accountkuber8aa6`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: accountkuber8aa6
        container-registry-url: accountreg.azurecr.io
        container-registry-username: ${{ secrets.acr_accountreg_username }}
        container-registry-password: ${{ secrets.acr_accountreg_password }}
        secret-name: accountkuberdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: accountkuber8aa6
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          accountreg.azurecr.io/accountkuber:${{ github.sha }}
        imagepullsecrets: |
          accountkuberdockerauth
